kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Ingress:
    - Egress:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                ns: test-one
          port: 8080